export {default as NavBar} from "./NavBar.jsx";
export {default as Action} from "./Action.jsx";
export {default as Hero} from "./Hero.jsx";
export {default as Model} from "./Model.jsx";
export {default as Contact} from "./Contact.jsx";
export {default as Footer} from "./Footer.jsx"
export {default as Pass} from "./Pass.jsx";
export {default as Services} from "./Services.jsx"
export {default as About} from "./About.jsx"